dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: "VBGqa2dSBmvrZFLUGJh+jFWAElrOGeLay3IaeDFTKqq2pmRgfNvwvdodxPa1a00sHCV4BXIdJFnf2YUvbxAC8kBNBrErGjCe4kes2rPd6FHCfFdtZMmpTr2k+OncMKWf/33bjxZCy6tvQP36td3YEn3weQcxmXjY+wI3rBvkCiSUCWFmPk9JWUsF85HJ4cwsrmNxPE9AkHKcohj9tqkjUG7rNEAhq3oNQgx4PZUpj3W5uPGJ78+GCvWBxf2BjrLTcPN4tWX2N1Xi02/8sZEsAfjGlr/LAnEZCRmMw1H6lk1mdYgrhhoCM9aVnAYqWH64ckhnpij2d8VxGrnPogcpRipUuYqT00xdgEkVb84Z0olsgJUCUn7cXNXUQq2tZ0ahEmKKDi0+y/jCWBt/ZyH4VbFMRDRsJq6+LiHI2rGMASlH/2XtcRmksK5WldRYcKrnr0KYhv8j/kaqxbHd51pFykx9vSgeC4NZQzjFn/vWZKbuiN7SNQR+Esdtp6XdOQaYWUf8AdL5w7342ARJZ7HL/wFd0Bi7LNn+pXmFEEqqQ8eSQIR75L0oJsXb569OYt4zjegIw77bwZqu5fohMmPk0ufmp5Z+nkapfP+GJ8KMY10RL7qk+oK22SP8b7Pyzm0xsqIhN/YJrTsiNM/7lQ6zIDbcaKaLZRB1sLMPfcytwAY="
  app: $APP